### ISSUE TITLE
Refactor samples

### ISSUE THREAD

**Issue by filipeesch** [Farfetch/kafkaflow#118]
Today we have only three samples. We need samples more focused in specific functionalities

**Comment by yzorg** [comment]
For Kafka projects an sample of enterprise style configuration (dev, staging, and production configuration for brokers/bootstrap, not just hard-coded "localhost:5092").

Other possible candidates for config: # workers, batch size, batch wait seconds, etc.  I'm seeing the same things set via most samples and readme code blocks.

P.S. I've noticed lack of config opinions across many Kafka dotnet OSS, including Confluent.  Any reasons why?  Or is it just "separation of duties"?  Most other enterprise offerings for dotnet have out-of-box `FooOptions` that can be bound and used by app code, any interest in offering that for Kafka dotnet?

**Comment by filipeesch** [comment]
Hi @yzorg, thanks for the feedback!

We intend to create a more enterprise sample, getting the values from a config file and having different environments, like a real application.

About the config values. It is more a "separation of duties", as you said. It will depend on the application, what the application does, how many instances the app has, the CPU and RAM resources each instance has, which database is used (or if a database is used) and so on. It is important to understand what each config does, choose some values as a baseline and change them to find the most optimized values for each case.
