### ISSUE TITLE
BatchConsume: IServiceProvider injected in a succeeding middleware throws object disposed, while IServiceScopeFactory works fine

### ISSUE THREAD

**Issue by rho-cassiopeiae** [Farfetch/kafkaflow#296]
IServiceScopeFactory works as expected, whereas IServiceProvider only works sometimes.

```c#
// ...
                    services.AddKafkaFlowHostedService(builder => builder
                        .UseConsoleLog()
                        .AddCluster(config => config
                            .WithBrokers(new[] { "..." })
                            .AddConsumer(consumer => consumer
                                .Topic("...")
                                .WithGroupId("...")
                                .WithWorkersCount(1)
                                .WithBufferSize(1000)
                                .AddMiddlewares(middlewares => middlewares
                                    .Add<ErrorHandlingMiddleware>()
                                    .AddSerializer<JsonCoreSerializer, MessageTypeResolver>()
                                    .BatchConsume(1000, TimeSpan.FromSeconds(5))
                                    .Add<BatchMessageHandler>()
                                )
                            )
                        )
```
```c#
    internal class BatchMessageHandler : IMessageMiddleware
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly ILogHandler _logger;

        public BatchMessageHandler(
            IServiceProvider serviceProvider,
            ILogHandler logger
        )
        {
            _serviceProvider = serviceProvider;
            _logger = logger;
        }

        public async Task Invoke(IMessageContext context, MiddlewareDelegate next)
        {
            var messages = context
                .GetMessagesBatch()
                .Select(m => (
                    Message: (SyncMessage) m.Message.Value,
                    Operation: m.Headers.GetString("op") == "upd" ? OperationType.Update : OperationType.Delete
                ));

            var groups = messages.GroupBy(m => (m.Message.IDMain, m.Message.IDSecondary));
            var changesToApply = groups.Select(group => group.Last()).ToList();
            if (changesToApply.Any())
            {
                using var scope = _serviceProvider.CreateScope(); // throws here
                var repo = scope.ServiceProvider.GetRequiredService<ISomeRepository>();

                // ...
            }

            await next(context);
        }
```

**Comment by gsferreira** [comment]
Hi @rho-cassiopeiae!

Thanks for submitting the issue.

Why do you need to create a new Scope? Asking that to understand the intent. Do you know that the Middleware is already invoked in the context of a new [Scope](https://github.com/Farfetch/kafkaflow/blob/c7663c38e0482ea51c1c332b2755d0d6a8ecd110/src/KafkaFlow/Consumers/ConsumerWorker.cs#L77)?

I could reproduce the exception. 
KafkaFlow executes the middleware inside of a Dependency Resolver Scope. 
You can see [here](https://github.com/Farfetch/kafkaflow/blob/c7663c38e0482ea51c1c332b2755d0d6a8ecd110/src/KafkaFlow/Consumers/ConsumerWorker.cs#L81) that the scope is disposed, causing the destruction of ServiceProvide while the Middleware is the same.

@filipeesch any idea if there's anything to do here?

**Comment by rho-cassiopeiae** [comment]
@gsferreira 
my understanging was that middleware is created with the lifetime `ConsumerOrProducer` by default, which I thought to basically mean singleton for the lifetime of the consumer? Is it wrong?

I wanted to do what I always do when using `IHostedService` in ASP.NET Core: inject `IServiceProvider`, manually create a scope, and resolve `DbContext` from it. Have to do it this way because `IHostedService` is a singleton but `DbContext` is scoped, therefore injecting `DbContext` directly would result in it also becoming a singleton.

**Comment by ruiqbarbosa** [comment]
We have added this topic to the _How Batch Consume Works_ section in the repository's documentation, addressing the concern. This allows us to consider the issue closed. You can find the relevant documentation at this [link](https://github.com/Farfetch/kafkaflow/blob/master/website/docs/guides/middlewares/batch-consume-middleware.md#how-to-use-it). If you have any further questions, feel free to reach out. Thank you for your contribution to the project.
