### ISSUE TITLE
Docs ambigious in function of Typed Handlers

### ISSUE THREAD

**Issue by douglasg14b** [Farfetch/kafkaflow#307]
The docs for Typed Handler Middleware docs make use of the word `type` without a clear definition and source of `type`. Unfortunately there are many possible definitions of what `type` means here :/

Can this be clarified?

For instance:

Is `type` the literal `Type` of the model? If so, then how is that communicated? Is that communicated though a value on the message? Is that determined via schema (Will that work without using Avro?), does it rely on duck typing?

**Comment by filipeesch** [comment]
Hi @douglasg14b ,

the Type means the message type. It helps when you have a topic with different message types. The consumer's first middleware receives the message as a byte[], after the serialization middleware, the message will be a typed class, and the TypedHandler route the message to a specific class to be processed (the handler)

**Comment by douglasg14b** [comment]
Thanks for the reply @filipeesch 

This does however skip over the meat of my query 😅 

Which is defining `message type`, unfortunately "the Type means the message type" still leaves that ambiguous.

Essentially:

> after the serialization middleware, the message will be a typed class

Is akin to the "finish the owl meme". Critical process & assumptions exist in between `byte[] -> MyClassInstance`, mainly in what information is required for the serializer to determine the class type.

I could cut down my question to just:

> Is type the literal Type of the model? If so, then how is that communicated? Is that communicated though a value on the message or the event? If so, what property? Is that determined via schema (Will that work without using Avro?), does it rely on duck typing?

**Comment by filipeesch** [comment]
> Is akin to the "finish the owl meme". Critical process & assumptions exist in between byte[] -> MyClassInstance, mainly in what information is required for the serializer to determine the class type.

Using ScemaRegistry, the schema is read from there, the first 5 bytes of the message is the SchemaId registered on the Schema Registry.

Using other serializers with no Schema Registry we use the DefaultMessageTypeResolver to write/read some headers to identify the message type, you can write your own TypeResolver implementing the IMessageTypeResolver interface and using it in the AddSerializer method in the consumer/producer middlewares.
