### ISSUE TITLE
Migrate Samples and Tests projects to .NET 6

### ISSUE THREAD

**Issue by gsferreira** [Farfetch/kafkaflow#322]
### Is your request related to a problem you have?

In December, .NET 3.1 will reach EOL.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

### Describe the solution you'd like

Change the framework for Sample and Test projects to .NET 6, the current LTS version.

### Are you able to help bring it to life and contribute with a Pull Request?

Yes

**Comment by ailtonguitar** [comment]
I'll close this issue due to all projects are already in .net6
