### ISSUE TITLE
[Feature Request]: Missing SslCaPem configuration

### ISSUE THREAD

**Issue by kYann** [Farfetch/kafkaflow#378]
### Is your request related to a problem you have?

We are trying to connect using SSL. We don't use file but pass ssl keys using an env variable. We need to set the SslCaPem. And it's not available on kafkaflow

### Describe the solution you'd like

Add SslCaPem connection configuration

### Are you able to help bring it to life and contribute with a Pull Request?

Yes

**Comment by kjsulls** [comment]
@kYann Great to see this come to life.  We also need this setting soon.
