### ISSUE TITLE
Bump System.Text.Json from 4.7.x to 6.0.x

### ISSUE THREAD

**Issue by ArminShoeibi** [Farfetch/kafkaflow#386]
### Is your request related to a problem you have?

Hello folks,

We're planning to use KafkaFlow in our microservices, and I'm thrilled to contribute to its development.

We can update System.Text.Json from version 4.7.x to 6.0.x while maintaining backward compatibility with .NET Framework 4.6.1 and .NET Standard 2.0

### Describe the solution you'd like
As is:
![image](https://user-images.githubusercontent.com/68565441/227369636-7d2b25b4-dfa0-4413-8369-9a71806c31fc.png)

To be:
![image](https://user-images.githubusercontent.com/68565441/227369497-74a79e79-9e9c-41c2-8708-6dbc23704b3c.png)

If you folks agree, I can make a PR.

### Are you able to help bring it to life and contribute with a Pull Request?

Yes

**Comment by ArminShoeibi** [comment]
Folks, Any feedback?
@filipeesch
@dougolima
@gsferreira

**Comment by josephpedro** [comment]
That will break compatibility with applications in .Net Core v3.0.
Maybe this could be added to Milestone 3.0.0? https://github.com/Farfetch/kafkaflow/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.0.0

**Comment by ailtonguitar** [comment]
I'll close this PR since it is already in version 6.x
