### ISSUE TITLE
Bump Confluent packages to 2.1.1

### ISSUE THREAD

**Issue by ArminShoeibi** [Farfetch/kafkaflow#388]
### Is your request related to a problem you have?

Hello folks,

Right now KafkaFlow projects are using Confluent packages with version 1.9.3
We can bump them to 2.1.1

Release note:
https://github.com/confluentinc/confluent-kafka-dotnet/releases/tag/v2.1.1

### Describe the solution you'd like

References:

- https://www.nuget.org/packages/Confluent.Kafka/2.1.1
- https://www.nuget.org/packages/Confluent.SchemaRegistry/2.1.1
- https://www.nuget.org/packages/Confluent.SchemaRegistry.Serdes.Avro/2.1.1
- https://www.nuget.org/packages/Confluent.SchemaRegistry.Serdes.Protobuf/2.1.1
- https://www.nuget.org/packages/Confluent.SchemaRegistry.Serdes.Json/2.1.1

### Are you able to help bring it to life and contribute with a Pull Request?

Yes

**Comment by toralux** [comment]
Confluent.Kafka package 1.9.3 doesn't support multiple CA certificates, but Confluent.Kafka 2.1.0 does, so I cannot use KafkaFlow with my current setup. 

Please upgrade KafkaFlow to use the more recent Confluent.Kafka 2.1.0. Thanks.

**Comment by toralux** [comment]
Any news on this one? For now we have to stick with Confluent.Kafka instead of KafkaFlow...
