### ISSUE TITLE
[Bug Report]: TypedHandlerMiddleware.WithHandlerLifetime(Scoped) scope not created

### ISSUE THREAD

**Issue by molszews** [Farfetch/kafkaflow#389]
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

It is possible to register typed handlers using `InstanceLifetime.Scoped`, the intuition behind that is that each handler and its dependencies would be scoped to that handler invocation, but that is not truth as the scope is created once per `ConsumerWorker`. The outcome is that if you have registered two handlers for the same message type, they would share scope, use the same dependencies (as long as they were registered with scope lifetime) and potentially cause threading issues as typed handlers are created using `Task.WhenAll`.
As the option to specify lifetime is called `WithHandlerLifetime`, I would suggest to run `CreateScope` before executing actual handler when appropriate.

### Steps to reproduce

1. Define consumer 

                m.AddTypedHandlers(h => h
                    .WithHandlerLifetime(InstanceLifetime.Scoped)

1.  Register multiple handlers for same message type, let them share dependency registered with lifetime = scope
1.  Trigger handlers by sending message to the topic, both handlers will be fired with shared dependency object, verify by checking hash code

### Expected behavior

Handlers will receive different instances of the dependency

### Actual behavior

Handlers receive the same instance of the dependency

### KafkaFlow version

2.2.15

**Comment by kjsulls** [comment]
@molszews I too am experiencing this issue, rather using BatchConsume in conjunction.  I am processing in parallel and expecting each time I call next(item) the typed handler would create its own scoped instance but that is not the case.  It seems to be behaving like a scoped instance per batch consume middleware invocation.

**Comment by molszews** [comment]
on the other hand, if it is desired to share the dependencies, could we have an option to opt-in for serial execution of typed handlers? so instead of spawning all tasks at once ([src](https://github.com/Farfetch/kafkaflow/blob/master/src/KafkaFlow.TypedHandler/TypedHandlerMiddleware.cs#L31)) they would be run one by one, thus eliminating potential issues with concurrent access to the same instances of handler dependencies

**Comment by molszews** [comment]
just another comment: my use case for custom middleware is to read user data from message header and then populate UserId in scope-registered UserContext object. Creating new scope per typed handler would probably mean that middleware won't be working anymore.

**Comment by BRGRLL99** [comment]
Hello @molszews, I'm starting to look into this issue, could you please give us a more complete "sample" in order for this to be more easily reproduced on our side?

**Comment by johnsonlu** [comment]
@molszews for your use case, maybe you can register the type handler as `Transient`?

**Comment by lpcouto** [comment]
> on the other hand, if it is desired to share the dependencies, could we have an option to opt-in for serial execution of typed handlers? so instead of spawning all tasks at once ([src](https://github.com/Farfetch/kafkaflow/blob/master/src/KafkaFlow.TypedHandler/TypedHandlerMiddleware.cs#L31)) they would be run one by one, thus eliminating potential issues with concurrent access to the same instances of handler dependencies

Regarding this, if you want to avoid parallel execution, you can, either define a single worker or, in version 3, you can create a distribution strategy for a subset of messages - [reference](https://farfetch.github.io/kafkaflow/docs/guides/consumers/#distribution-strategy).

**Comment by lpcouto** [comment]
> on the other hand, if it is desired to share the dependencies, could we have an option to opt-in for serial execution of typed handlers? so instead of spawning all tasks at once ([src](https://github.com/Farfetch/kafkaflow/blob/master/src/KafkaFlow.TypedHandler/TypedHandlerMiddleware.cs#L31)) they would be run one by one, thus eliminating potential issues with concurrent access to the same instances of handler dependencies


Regarding this, if you want to avoid parallel execution, you can, either define a single worker or, in version 3, you can create a distribution strategy for a subset of messages - [reference](https://farfetch.github.io/kafkaflow/docs/guides/consumers/#distribution-strategy).

**Comment by mhkolk** [comment]
I have issues with EF Core DbContext injection in IMessageMiddleware either with constructor injection or through creating scope and using service provider - in both case the same instance of DbContext is returned resulting in a known EF context issue 

> System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

Apparently this comes from the fact only one instance of Middleware is created thus resulting in the same instance of DbContext being used to process all the messages.

The issue is more obvious when a large number of messages gets processed at the same time.

**Comment by lpcouto** [comment]
Hi @mhkolk ,
Please register your middleware as transient and let us know if that solves your issues:

**Comment by mhkolk** [comment]
> Hi @mhkolk , Please register your middleware as transient and let us know if that solves your issues:
> 
> ```
> .AddMiddlewares(
>     middlewares => middlewares
>         .AddDeserializer<ProtobufNetDeserializer>()
>         .Add<MyMiddleware>(MiddlewareLifetime.Transient)
> )
> ```

This did help indeed. I made a PR updating a part of middleware docs because this is so easy to miss. Since it wasn't mentioned anywhere I didn't bother to check if overloads to Add exist.

**Comment by lpcouto** [comment]
Hi @molszews 

If you're still experiencing this issue or have any additional information to share, please feel free to let us know.

However, if we don't receive any updates or feedback from you within the next 5 business days, we may need to consider closing this issue. Please understand that this is not a final decision, and you can always reopen the issue or create a new one in the future.

We appreciate your contribution to our project and look forward to hearing from you soon. If you have any questions or need further assistance, don't hesitate to reach out.

**Comment by molszews** [comment]
Hi, I believe using `lifetime: MiddlewareLifetime.Message` solved the issue for me, thanks for your support!

**Comment by molszews** [comment]
Closing as resolved
