### ISSUE TITLE
[Bug Report]: ConsumerBatch do store offsets when exception next middleware

### ISSUE THREAD

**Issue by vkuzugashev** [Farfetch/kafkaflow#422]
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

ConsumerBatch do store offsets when exception next middleware.
I,m thing this bag. In my case messages consumed into batch. If batch stored to database success on next middleware, then messages offset must stored to kafka. If batch store on next middleware with exception, then all message offset must not store to kafka.

Now, when batch stored on next middleware with exception, then all messages offset store to kafka:

BatchConsumeMiddleware.cs line 106.
`
foreach (var messageContext in localBatch)
{
     messageContext.ConsumerContext.StoreOffset();
}
`

### Steps to reproduce

1. Add ConsumeBatch
2. Add next middleware with throw exception

### Expected behavior

If get exception on next middleware, then all message offsets, not be stored to kafka

### Actual behavior

get exception on next middleware and all messages offsets will stored to kafka

### KafkaFlow version

no

**Comment by JoaoRodriguesGithub** [comment]
Hi @vkuzugashev ,

We will be closing this issue since the question has been answered. Please feel free to respond to this message or reopen the issue if you'd like to continue the discussion or if you've encountered any new developments related to it.

Thank you for your contribution.
