### ISSUE TITLE
[Feature Request]: Add extensibility to OpenTelemetry tracing

### ISSUE THREAD

**Issue by simaoribeiro** [Farfetch/kafkaflow#465]
### Is your request related to a problem you have?

The users of the framework may want to include additional attributes in the tracing spans being created on message produce and consume, e.g.: message headers.

### Describe the solution you'd like

Add an extensibility option when configuring OpenTelemetry (`AddOpenTelemetry()`) to include additional attributes

### Are you able to help bring it to life and contribute with a Pull Request?

Yes

**Comment by AlexeyRaga** [comment]
It'd be great if it'd be possible to "automagically" add message type, too ;)
