### ISSUE TITLE
[Bug Report]: Deserializer does not trigger next middleware in pipeline

### ISSUE THREAD

**Issue by sdi-apmm** [Farfetch/kafkaflow#494]
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

.AddDeserializer middleware from KafkaFlow does not trigger next middleware in pipeline. If I remove it, the middlewares get triggered but obviously the data is not deserialised.  The documentation is ALSO very misleading. In your consumer sample you use .AddSerializer in your consumer definition while the solution expects .AddDeserializer other it throws error

![image](https://github.com/Farfetch/kafkaflow/assets/110403263/ea43e8b9-b676-4250-928b-fad10dc40d17)

### Steps to reproduce

1. Add inbuilt deserialier for json
2. Add custom middlewares

### Expected behavior

For the data to be deserialized and next middleware in pipeline to get triggered

### Actual behavior

Nothing happens, unless I remove the deserialised middleware but then my other middlewares obviously break because the message is not in expected format

### KafkaFlow version

3.0.1

**Comment by joelfoliveira** [comment]
Hi @sdi-apmm 

Please check that the object type being sent from the producer application to the consumer application has the same full qualified namespace. This is necessary for the serializer to do the deserialization automatically.

If the full qualified namespace is not shared between producer and consumer objects, a custom MessageTypeResolver can be created to map the correct type of object to deserialize (documentation [here](https://farfetch.github.io/kafkaflow/docs/guides/middlewares/serializer-middleware#creating-a-message-type-resolver)).

**Comment by joelfoliveira** [comment]
Hi @sdi-apmm ,

We will be closing this issue since the question has been answered. Please feel free to respond to this message or reopen the issue if you'd like to continue the discussion or if you've encountered any new developments related to it.

Thank you for your contribution.
