### ISSUE TITLE
[Bug Report]: schema-registry service fails because broker is not available yet

### ISSUE THREAD

**Issue by Bahri-Haythem** [Farfetch/kafkaflow#522]
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

When trying to run docker-compose up, the schema-registry service fails because the broker is not available yet. I think this could be fixed by adding a depends_on or creating a health check.

### Steps to reproduce

1. pull the project
2. run ```docker-compose up -d```

### Expected behavior

running directly without having to restart the service.

### Actual behavior

the schema-registry service fails (not necessarily always) and this is the output: 
```2024-02-14 11:54:58 49112 [kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Connection to node -1 (broker/172.18.0.3:29092) could not be established. Broker may not be available.```

### KafkaFlow version

3.0.3

**Comment by lpcouto** [comment]
Hi, @Bahri-Haythem,
Although this issue has never occurred on our side, we added health check to broker, and schema registry now depends on broker's healthy condition. Please let us know if that fixes this issue on your side.
